### ISSUE TITLE
Documentation is wrong about how to populate keys

### ISSUE THREAD

**Issue by juniorz** [hockeypuck/hockeypuck.github.io#1]
The "Populating" page [1] mentions the following command to import keys into the keyserver:

`hockeypuck -config /etc/hockeypuck/hockeypuck.conf /path/to/keyfiles/\*.pgp`

But on version 2, it seems to be:

`hockeypuck-load -config /etc/hockeypuck/hockeypuck.conf /path/to/keyfiles/\*.pgp`

1 - https://hockeypuck.github.io/populating.html

**Comment by 4a6f656c** [comment]
This is not actually fixed - https://hockeypuck.github.io/populating.html still shows the incorrect `hockeypuck` command. Not sure if a process got missed or if the fix landed in the wrong branch (gh-pages vs master).
