### ISSUE TITLE
Missing command on populating keys documentation page

### ISSUE THREAD

**Issue by mvanbaak** [hockeypuck/hockeypuck.github.io#5]
The current populating documentation page does not mention we have to run hockeypuck-pbuild to rebuild the recon database.

**Comment by MarcelWaldvogel** [comment]
I just set up a new keyserver and did not have to run `hockeypuck-pbuild`. Running `hockeypuck-load` (with a location for the ptree already specifiec in the config file) created the prefix tree.

So this probably can be closed.
